# Generated by Django 5.1.7 on 2025-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='internetUsage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='levelAwareness',
        ),
        migrations.AddField(
            model_name='user',
            name='awareness_level',
            field=models.CharField(choices=[('none', 'Нулевой'), ('basic', 'Базовый'), ('medium', 'Средний'), ('high', 'Высокий')], default='Нулевой', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cyber_crimes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='cyber_experience',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('unsure', 'Не уверен(а)')], default='Да', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_usage',
            field=models.CharField(choices=[('always', 'Постоянно'), ('1-3', '1-3 раза в день'), ('4-10', '4-10 раз в день'), ('rare', 'Реже')], default='Постоянно', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('<18', 'Менее 18 лет'), ('18-25', '18-25 лет'), ('26-35', '26-35 лет'), ('36-50', '36-50 лет'), ('51-64', '51-64 лет'), ('65+', 'Более 65 лет')], default='Менее 18 лет', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(choices=[('student', 'Учащийся/Студент'), ('it', 'IT/Технологии'), ('gov', 'Госслужба'), ('military', 'Военная служба'), ('edu', 'Образование/Наука'), ('health', 'Здравоохранение'), ('law', 'Правоохранительные органы'), ('services', 'Услуги'), ('business', 'Предпринимательская деятельность'), ('retired', 'Пенсионер'), ('housewife', 'Домохозяйка/молодая мама'), ('unemployed', 'Временно не работающий'), ('engineer', 'Инженер'), ('worker', 'Рабочий'), ('sales', 'Продажи'), ('creative', 'Творчество'), ('agriculture', 'Сельское хозяйство'), ('media', 'Медиа')], default='Временно не работающий', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('basic', 'Основное общее (до 9 класса)'), ('secondary', 'Среднее общее (до 11 класса)'), ('college', 'Среднее специальное'), ('higher', 'Высшее'), ('phd', 'Ученая степень'), ('none', 'Отсутствует')], default='Высшее', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Женский'), ('M', 'Мужской')], default='Женский', max_length=1),
        ),
    ]
