# Generated by Django 5.1.7 on 2025-04-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatsession_topic_remove_testquestion_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
