# Generated by Django 5.1.7 on 2025-04-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_postauthor_securitypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('description', models.TextField(verbose_name='Описание темы')),
                ('resources', models.TextField(help_text='Ссылки и материалы для изучения темы', verbose_name='Рекомендации и ресурсы')),
            ],
        ),
        migrations.AddField(
            model_name='testquestion',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.questiontopic', verbose_name='Тема вопроса'),
        ),
    ]
